/* Decks personnalisés — produit par zombicide-decks.html
   Déposer dans zombicide_fichiers/decks/decks.js
   `boites` ne sert qu'à l'éditeur : il retient de quelles boîtes les
   quantités ont été tirées. Le jeu ne lit que `nom`, `equip` et `spawn`. */
window.ZBP_DECKS = {
  decks: [
  {
    nom: "Boîte de base",
    boites: {"Black Plague":"tout"},
    equip: {
      "shortbow": {deck:1, start:1, vault:0},
      "shortsword": {deck:1, start:3, vault:0},
      "manablast": {deck:1, start:1, vault:0},
      "hammer": {deck:1, start:1, vault:0},
      "aaahh": {deck:4, start:0, vault:0},
      "apples": {deck:2, start:0, vault:0},
      "meat": {deck:2, start:0, vault:0},
      "water": {deck:2, start:0, vault:0},
      "axe": {deck:2, start:0, vault:0},
      "dagger": {deck:4, start:0, vault:0},
      "sword": {deck:2, start:0, vault:0},
      "greatsword": {deck:2, start:0, vault:0},
      "crossbow": {deck:2, start:0, vault:0},
      "handxbow": {deck:2, start:0, vault:0},
      "repxbow": {deck:2, start:0, vault:0},
      "longbow": {deck:2, start:0, vault:0},
      "deathstrike": {deck:2, start:0, vault:0},
      "fireball": {deck:2, start:0, vault:0},
      "lightning": {deck:2, start:0, vault:0},
      "leather": {deck:2, start:0, vault:0},
      "chainmail": {deck:2, start:0, vault:0},
      "plate": {deck:1, start:0, vault:0},
      "shield": {deck:2, start:0, vault:0},
      "arrows": {deck:3, start:0, vault:0},
      "bolts": {deck:3, start:0, vault:0},
      "torch": {deck:4, start:0, vault:0},
      "bile": {deck:4, start:0, vault:0},
      "healing": {deck:1, start:0, vault:0},
      "invisibility": {deck:1, start:0, vault:0},
      "repulse": {deck:1, start:0, vault:0},
      "speed": {deck:1, start:0, vault:0},
      "inferno": {deck:0, start:0, vault:1},
      "orcxbow": {deck:0, start:0, vault:1},
      "axecarnage": {deck:0, start:0, vault:0},
      "bastardsword": {deck:0, start:0, vault:0},
      "chainlightning": {deck:0, start:0, vault:0},
      "chaoslongbow": {deck:0, start:0, vault:0},
      "deflectdagger": {deck:0, start:0, vault:0},
      "disintegrate": {deck:0, start:0, vault:0},
      "dragonblade": {deck:0, start:0, vault:0},
      "quakehammer": {deck:0, start:0, vault:0},
      "flamingsword": {deck:0, start:0, vault:0},
      "ironclad": {deck:0, start:0, vault:0},
      "quicksilver": {deck:0, start:0, vault:0},
      "shieldages": {deck:0, start:0, vault:0},
      "stormbow": {deck:0, start:0, vault:0},
      "transmut": {deck:0, start:0, vault:0},
      "vampxbow": {deck:0, start:0, vault:0},
      "aaahhorc": {deck:0, start:0, vault:0},
      "bonekukri": {deck:0, start:0, vault:0},
      "bonesword": {deck:0, start:0, vault:0},
      "curveddagger": {deck:0, start:0, vault:0},
      "deathgale": {deck:0, start:0, vault:0},
      "dwarfaxe": {deck:0, start:0, vault:0},
      "dwarfhammer": {deck:0, start:0, vault:0},
      "falchion": {deck:0, start:0, vault:0},
      "ghostsight": {deck:0, start:0, vault:0},
      "greataxe": {deck:0, start:0, vault:0},
      "lavaburst": {deck:0, start:0, vault:0},
      "lightningball": {deck:0, start:0, vault:0},
      "norseshield": {deck:0, start:0, vault:0},
      "norsesword": {deck:0, start:0, vault:0},
      "scimitar": {deck:0, start:0, vault:0},
      "spikedbow": {deck:0, start:0, vault:0},
      "steelbow": {deck:0, start:0, vault:0},
      "telekblast": {deck:0, start:0, vault:0},
      "tremor": {deck:0, start:0, vault:0},
      "warcleaver": {deck:0, start:0, vault:0}
    },
    spawn: [
      ["-","2R","5W","2B"],
      ["-","2B","5W","5W"],
      ["-","4W","3R","2R"],
      ["1W","1R","3B","3B"],
      ["1W","1B","4W","5W"],
      ["1W","2W","1R","3R"],
      ["2W","1R","1B","3B"],
      ["3W","1B","4W","6W"],
      ["1B","2W","2R","3R"],
      ["1B","2W","2B","5W"],
      ["1R","3W","3W","6W"],
      ["1R","3W","3W","5W"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1B","2W","2B","7W"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1W","2B","2W","7B"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["-","!W","!W","!W"],
      ["-","!W","!W","!W"],
      ["-","!B","!B","!B"],
      ["-","!R","!R","!R"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"]
    ]
  },
  {
    nom: "BP + départ (WB + GH)",
    boites: {"Black Plague":"tout","Wulfsburg":"depart","Green Horde":"depart"},
    equip: {
      "shortbow": {deck:1, start:2, vault:0},
      "shortsword": {deck:1, start:8, vault:0},
      "manablast": {deck:1, start:2, vault:0},
      "hammer": {deck:1, start:1, vault:0},
      "aaahh": {deck:4, start:0, vault:0},
      "apples": {deck:2, start:0, vault:0},
      "meat": {deck:2, start:0, vault:0},
      "water": {deck:2, start:0, vault:0},
      "axe": {deck:2, start:0, vault:0},
      "dagger": {deck:4, start:0, vault:0},
      "sword": {deck:2, start:0, vault:0},
      "greatsword": {deck:2, start:0, vault:0},
      "crossbow": {deck:2, start:0, vault:0},
      "handxbow": {deck:2, start:0, vault:0},
      "repxbow": {deck:2, start:0, vault:0},
      "longbow": {deck:2, start:0, vault:0},
      "deathstrike": {deck:2, start:0, vault:0},
      "fireball": {deck:2, start:0, vault:0},
      "lightning": {deck:2, start:0, vault:0},
      "leather": {deck:2, start:0, vault:0},
      "chainmail": {deck:2, start:0, vault:0},
      "plate": {deck:1, start:0, vault:0},
      "shield": {deck:2, start:0, vault:0},
      "arrows": {deck:3, start:0, vault:0},
      "bolts": {deck:3, start:0, vault:0},
      "torch": {deck:4, start:0, vault:0},
      "bile": {deck:4, start:0, vault:0},
      "healing": {deck:1, start:0, vault:0},
      "invisibility": {deck:1, start:0, vault:0},
      "repulse": {deck:1, start:0, vault:0},
      "speed": {deck:1, start:0, vault:0},
      "inferno": {deck:0, start:0, vault:1},
      "orcxbow": {deck:0, start:0, vault:1},
      "axecarnage": {deck:0, start:0, vault:0},
      "bastardsword": {deck:0, start:0, vault:0},
      "chainlightning": {deck:0, start:0, vault:0},
      "chaoslongbow": {deck:0, start:0, vault:0},
      "deflectdagger": {deck:0, start:0, vault:0},
      "disintegrate": {deck:0, start:0, vault:0},
      "dragonblade": {deck:0, start:0, vault:0},
      "quakehammer": {deck:0, start:0, vault:0},
      "flamingsword": {deck:0, start:0, vault:0},
      "ironclad": {deck:0, start:0, vault:0},
      "quicksilver": {deck:0, start:0, vault:0},
      "shieldages": {deck:0, start:0, vault:0},
      "stormbow": {deck:0, start:0, vault:0},
      "transmut": {deck:0, start:0, vault:0},
      "vampxbow": {deck:0, start:0, vault:0},
      "aaahhorc": {deck:0, start:0, vault:0},
      "bonekukri": {deck:0, start:0, vault:0},
      "bonesword": {deck:0, start:0, vault:0},
      "curveddagger": {deck:0, start:0, vault:0},
      "deathgale": {deck:0, start:0, vault:0},
      "dwarfaxe": {deck:0, start:0, vault:0},
      "dwarfhammer": {deck:0, start:0, vault:0},
      "falchion": {deck:0, start:0, vault:0},
      "ghostsight": {deck:0, start:0, vault:0},
      "greataxe": {deck:0, start:0, vault:0},
      "lavaburst": {deck:0, start:0, vault:0},
      "lightningball": {deck:0, start:0, vault:0},
      "norseshield": {deck:0, start:0, vault:0},
      "norsesword": {deck:0, start:1, vault:0},
      "scimitar": {deck:0, start:0, vault:0},
      "spikedbow": {deck:0, start:1, vault:0},
      "steelbow": {deck:0, start:0, vault:0},
      "telekblast": {deck:0, start:1, vault:0},
      "tremor": {deck:0, start:0, vault:0},
      "warcleaver": {deck:0, start:0, vault:0}
    },
    spawn: [
      ["-","2R","5W","2B"],
      ["-","2B","5W","5W"],
      ["-","4W","3R","2R"],
      ["1W","1R","3B","3B"],
      ["1W","1B","4W","5W"],
      ["1W","2W","1R","3R"],
      ["2W","1R","1B","3B"],
      ["3W","1B","4W","6W"],
      ["1B","2W","2R","3R"],
      ["1B","2W","2B","5W"],
      ["1R","3W","3W","6W"],
      ["1R","3W","3W","5W"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1B","2W","2B","7W"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1W","2B","2W","7B"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["-","!W","!W","!W"],
      ["-","!W","!W","!W"],
      ["-","!B","!B","!B"],
      ["-","!R","!R","!R"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"]
    ]
  },
  {
    nom: "BP + WB + équipement de départ GH",
    boites: {"Black Plague":"tout","Wulfsburg":"tout","Green Horde":"depart"},
    equip: {
      "shortbow": {deck:1, start:2, vault:0},
      "shortsword": {deck:1, start:8, vault:0},
      "manablast": {deck:1, start:2, vault:0},
      "hammer": {deck:1, start:1, vault:0},
      "aaahh": {deck:4, start:0, vault:0},
      "apples": {deck:2, start:0, vault:0},
      "meat": {deck:2, start:0, vault:0},
      "water": {deck:2, start:0, vault:0},
      "axe": {deck:2, start:0, vault:0},
      "dagger": {deck:4, start:0, vault:0},
      "sword": {deck:2, start:0, vault:0},
      "greatsword": {deck:2, start:0, vault:0},
      "crossbow": {deck:2, start:0, vault:0},
      "handxbow": {deck:2, start:0, vault:0},
      "repxbow": {deck:2, start:0, vault:0},
      "longbow": {deck:2, start:0, vault:0},
      "deathstrike": {deck:2, start:0, vault:0},
      "fireball": {deck:2, start:0, vault:0},
      "lightning": {deck:2, start:0, vault:0},
      "leather": {deck:2, start:0, vault:0},
      "chainmail": {deck:2, start:0, vault:0},
      "plate": {deck:1, start:0, vault:0},
      "shield": {deck:2, start:0, vault:0},
      "arrows": {deck:3, start:0, vault:0},
      "bolts": {deck:3, start:0, vault:0},
      "torch": {deck:4, start:0, vault:0},
      "bile": {deck:4, start:0, vault:0},
      "healing": {deck:1, start:0, vault:0},
      "invisibility": {deck:1, start:0, vault:0},
      "repulse": {deck:1, start:0, vault:0},
      "speed": {deck:1, start:0, vault:0},
      "inferno": {deck:0, start:0, vault:1},
      "orcxbow": {deck:0, start:0, vault:1},
      "axecarnage": {deck:1, start:0, vault:0},
      "bastardsword": {deck:2, start:0, vault:0},
      "chainlightning": {deck:2, start:0, vault:0},
      "chaoslongbow": {deck:1, start:0, vault:0},
      "deflectdagger": {deck:1, start:0, vault:0},
      "disintegrate": {deck:2, start:0, vault:0},
      "dragonblade": {deck:1, start:0, vault:0},
      "quakehammer": {deck:1, start:0, vault:0},
      "flamingsword": {deck:1, start:0, vault:0},
      "ironclad": {deck:1, start:0, vault:0},
      "quicksilver": {deck:1, start:0, vault:0},
      "shieldages": {deck:1, start:0, vault:0},
      "stormbow": {deck:1, start:0, vault:0},
      "transmut": {deck:1, start:0, vault:0},
      "vampxbow": {deck:1, start:0, vault:0},
      "aaahhorc": {deck:0, start:0, vault:0},
      "bonekukri": {deck:0, start:0, vault:0},
      "bonesword": {deck:0, start:0, vault:0},
      "curveddagger": {deck:0, start:0, vault:0},
      "deathgale": {deck:0, start:0, vault:0},
      "dwarfaxe": {deck:0, start:0, vault:0},
      "dwarfhammer": {deck:0, start:0, vault:0},
      "falchion": {deck:0, start:0, vault:0},
      "ghostsight": {deck:0, start:0, vault:0},
      "greataxe": {deck:0, start:0, vault:0},
      "lavaburst": {deck:0, start:0, vault:0},
      "lightningball": {deck:0, start:0, vault:0},
      "norseshield": {deck:0, start:0, vault:0},
      "norsesword": {deck:0, start:1, vault:0},
      "scimitar": {deck:0, start:0, vault:0},
      "spikedbow": {deck:0, start:1, vault:0},
      "steelbow": {deck:0, start:0, vault:0},
      "telekblast": {deck:0, start:1, vault:0},
      "tremor": {deck:0, start:0, vault:0},
      "warcleaver": {deck:0, start:0, vault:0}
    },
    spawn: [
      ["-","2R","5W","2B"],
      ["-","2B","5W","5W"],
      ["-","4W","3R","2R"],
      ["1W","1R","3B","3B"],
      ["1W","1B","4W","5W"],
      ["1W","2W","1R","3R"],
      ["2W","1R","1B","3B"],
      ["3W","1B","4W","6W"],
      ["1B","2W","2R","3R"],
      ["1B","2W","2B","5W"],
      ["1R","3W","3W","6W"],
      ["1R","3W","3W","5W"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1B","2W","2B","7W"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1W","2B","2W","7B"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["-","!W","!W","!W"],
      ["-","!W","!W","!W"],
      ["-","!B","!B","!B"],
      ["-","!R","!R","!R"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"]
    ]
  },
  {
    nom: "Green Horde seul",
    boites: {"Green Horde":"tout"},
    equip: {
      "shortbow": {deck:0, start:0, vault:0},
      "shortsword": {deck:1, start:3, vault:0},
      "manablast": {deck:0, start:0, vault:0},
      "hammer": {deck:0, start:0, vault:0},
      "aaahh": {deck:0, start:0, vault:0},
      "apples": {deck:2, start:0, vault:0},
      "meat": {deck:2, start:0, vault:0},
      "water": {deck:2, start:0, vault:0},
      "axe": {deck:2, start:0, vault:0},
      "dagger": {deck:0, start:0, vault:0},
      "sword": {deck:0, start:0, vault:0},
      "greatsword": {deck:0, start:0, vault:0},
      "crossbow": {deck:2, start:0, vault:0},
      "handxbow": {deck:2, start:0, vault:0},
      "repxbow": {deck:2, start:0, vault:0},
      "longbow": {deck:2, start:0, vault:0},
      "deathstrike": {deck:0, start:0, vault:0},
      "fireball": {deck:0, start:0, vault:0},
      "lightning": {deck:0, start:0, vault:0},
      "leather": {deck:0, start:0, vault:0},
      "chainmail": {deck:2, start:0, vault:0},
      "plate": {deck:1, start:0, vault:0},
      "shield": {deck:2, start:0, vault:0},
      "arrows": {deck:3, start:0, vault:0},
      "bolts": {deck:3, start:0, vault:0},
      "torch": {deck:4, start:0, vault:0},
      "bile": {deck:4, start:0, vault:0},
      "healing": {deck:1, start:0, vault:0},
      "invisibility": {deck:0, start:0, vault:0},
      "repulse": {deck:1, start:0, vault:0},
      "speed": {deck:1, start:0, vault:0},
      "inferno": {deck:0, start:0, vault:0},
      "orcxbow": {deck:0, start:0, vault:0},
      "axecarnage": {deck:0, start:0, vault:0},
      "bastardsword": {deck:0, start:0, vault:0},
      "chainlightning": {deck:0, start:0, vault:0},
      "chaoslongbow": {deck:0, start:0, vault:0},
      "deflectdagger": {deck:0, start:0, vault:0},
      "disintegrate": {deck:0, start:0, vault:0},
      "dragonblade": {deck:0, start:0, vault:0},
      "quakehammer": {deck:0, start:0, vault:0},
      "flamingsword": {deck:0, start:0, vault:0},
      "ironclad": {deck:0, start:0, vault:0},
      "quicksilver": {deck:0, start:0, vault:0},
      "shieldages": {deck:0, start:0, vault:0},
      "stormbow": {deck:0, start:0, vault:0},
      "transmut": {deck:0, start:0, vault:0},
      "vampxbow": {deck:0, start:0, vault:0},
      "aaahhorc": {deck:4, start:0, vault:0},
      "bonekukri": {deck:0, start:0, vault:1},
      "bonesword": {deck:0, start:0, vault:1},
      "curveddagger": {deck:4, start:0, vault:0},
      "deathgale": {deck:2, start:0, vault:0},
      "dwarfaxe": {deck:0, start:0, vault:1},
      "dwarfhammer": {deck:2, start:0, vault:0},
      "falchion": {deck:2, start:0, vault:0},
      "ghostsight": {deck:1, start:0, vault:0},
      "greataxe": {deck:2, start:0, vault:0},
      "lavaburst": {deck:0, start:0, vault:1},
      "lightningball": {deck:2, start:0, vault:0},
      "norseshield": {deck:2, start:0, vault:0},
      "norsesword": {deck:1, start:1, vault:0},
      "scimitar": {deck:2, start:0, vault:0},
      "spikedbow": {deck:1, start:1, vault:0},
      "steelbow": {deck:0, start:0, vault:1},
      "telekblast": {deck:1, start:1, vault:0},
      "tremor": {deck:1, start:0, vault:0},
      "warcleaver": {deck:0, start:0, vault:1}
    },
    spawn: [
      ["-","2R","5W","2B"],
      ["-","2B","5W","5W"],
      ["-","4W","3R","2R"],
      ["1W","1R","3B","3B"],
      ["1W","1B","4W","5W"],
      ["1W","2W","1R","3R"],
      ["2W","1R","1B","3B"],
      ["3W","1B","4W","6W"],
      ["1B","2W","2R","3R"],
      ["1B","2W","2B","5W"],
      ["1R","3W","3W","6W"],
      ["1R","3W","3W","5W"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1B","2W","2B","7W"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1W","2B","2W","7B"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["-","!W","!W","!W"],
      ["-","!W","!W","!W"],
      ["-","!B","!B","!B"],
      ["-","!R","!R","!R"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"]
    ]
  },
  {
    nom: "Les trois boîtes mélangées",
    boites: {"Black Plague":"tout","Wulfsburg":"tout","Green Horde":"tout"},
    equip: {
      "shortbow": {deck:1, start:2, vault:0},
      "shortsword": {deck:2, start:8, vault:0},
      "manablast": {deck:1, start:2, vault:0},
      "hammer": {deck:1, start:1, vault:0},
      "aaahh": {deck:4, start:0, vault:0},
      "apples": {deck:4, start:0, vault:0},
      "meat": {deck:4, start:0, vault:0},
      "water": {deck:4, start:0, vault:0},
      "axe": {deck:4, start:0, vault:0},
      "dagger": {deck:4, start:0, vault:0},
      "sword": {deck:2, start:0, vault:0},
      "greatsword": {deck:2, start:0, vault:0},
      "crossbow": {deck:4, start:0, vault:0},
      "handxbow": {deck:4, start:0, vault:0},
      "repxbow": {deck:4, start:0, vault:0},
      "longbow": {deck:4, start:0, vault:0},
      "deathstrike": {deck:2, start:0, vault:0},
      "fireball": {deck:2, start:0, vault:0},
      "lightning": {deck:2, start:0, vault:0},
      "leather": {deck:2, start:0, vault:0},
      "chainmail": {deck:4, start:0, vault:0},
      "plate": {deck:2, start:0, vault:0},
      "shield": {deck:4, start:0, vault:0},
      "arrows": {deck:6, start:0, vault:0},
      "bolts": {deck:6, start:0, vault:0},
      "torch": {deck:8, start:0, vault:0},
      "bile": {deck:8, start:0, vault:0},
      "healing": {deck:2, start:0, vault:0},
      "invisibility": {deck:1, start:0, vault:0},
      "repulse": {deck:2, start:0, vault:0},
      "speed": {deck:2, start:0, vault:0},
      "inferno": {deck:0, start:0, vault:1},
      "orcxbow": {deck:0, start:0, vault:1},
      "axecarnage": {deck:1, start:0, vault:0},
      "bastardsword": {deck:2, start:0, vault:0},
      "chainlightning": {deck:2, start:0, vault:0},
      "chaoslongbow": {deck:1, start:0, vault:0},
      "deflectdagger": {deck:1, start:0, vault:0},
      "disintegrate": {deck:2, start:0, vault:0},
      "dragonblade": {deck:1, start:0, vault:0},
      "quakehammer": {deck:1, start:0, vault:0},
      "flamingsword": {deck:1, start:0, vault:0},
      "ironclad": {deck:1, start:0, vault:0},
      "quicksilver": {deck:1, start:0, vault:0},
      "shieldages": {deck:1, start:0, vault:0},
      "stormbow": {deck:1, start:0, vault:0},
      "transmut": {deck:1, start:0, vault:0},
      "vampxbow": {deck:1, start:0, vault:0},
      "aaahhorc": {deck:4, start:0, vault:0},
      "bonekukri": {deck:0, start:0, vault:1},
      "bonesword": {deck:0, start:0, vault:1},
      "curveddagger": {deck:4, start:0, vault:0},
      "deathgale": {deck:2, start:0, vault:0},
      "dwarfaxe": {deck:0, start:0, vault:1},
      "dwarfhammer": {deck:2, start:0, vault:0},
      "falchion": {deck:2, start:0, vault:0},
      "ghostsight": {deck:1, start:0, vault:0},
      "greataxe": {deck:2, start:0, vault:0},
      "lavaburst": {deck:0, start:0, vault:1},
      "lightningball": {deck:2, start:0, vault:0},
      "norseshield": {deck:2, start:0, vault:0},
      "norsesword": {deck:1, start:1, vault:0},
      "scimitar": {deck:2, start:0, vault:0},
      "spikedbow": {deck:1, start:1, vault:0},
      "steelbow": {deck:0, start:0, vault:1},
      "telekblast": {deck:1, start:1, vault:0},
      "tremor": {deck:1, start:0, vault:0},
      "warcleaver": {deck:0, start:0, vault:1}
    },
    spawn: [
      ["-","2R","5W","2B"],
      ["-","2B","5W","5W"],
      ["-","4W","3R","2R"],
      ["1W","1R","3B","3B"],
      ["1W","1B","4W","5W"],
      ["1W","2W","1R","3R"],
      ["2W","1R","1B","3B"],
      ["3W","1B","4W","6W"],
      ["1B","2W","2R","3R"],
      ["1B","2W","2B","5W"],
      ["1R","3W","3W","6W"],
      ["1R","3W","3W","5W"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1B","2W","2B","7W"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["1A","1R","5W","2B"],
      ["2W","1A","1B","3R"],
      ["2W","1B","1A","6W"],
      ["1W","3W","2R","1A"],
      ["1W","2R","3B","6W"],
      ["1R","1B","4W","5W"],
      ["1W","4W","2R","3B"],
      ["1B","1R","6W","2R"],
      ["1W","2B","2R","8W"],
      ["1W","2B","2W","7B"],
      ["1R","4W","4W","3B"],
      ["1B","3W","5W","3R"],
      ["-","!W","!W","!W"],
      ["-","!W","!W","!W"],
      ["-","!B","!B","!B"],
      ["-","!R","!R","!R"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["N","N","N","N"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"],
      ["D","D","D","D"]
    ]
  }
  ]
};
